version: '3'
services:
    pgadmin:
        container_name: pgadmin4_container
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            - "5050:80"

    nginx:
        image: nginx
        volumes:
            - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8000:80


    postgres:
        image: postgres:14
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: test
        ports:
            - '5432:5432'
        volumes:
            - ./db/db-data:/var/lib/postgresql/data
            # - ./backend/db:/docker-entrypoint-initdb.d


    backend:
        build: ./backend
        container_name: fastapi-application
        command: uvicorn app.main:app --port 8080
        environment:
            DB_NAME: test
            DB_USER: postgres
            DB_HOST: db
            DB_PASSWORD: postgres
        ports:
            - 8080:8080
        # tty: true
        # environment:
        #     PYTHONPATH: .
        #     DATABASE_URL: 'postgresql://{{postgres_user}}:{{postgres_password}}@postgres:5432/{{postgres_user}}'
        depends_on:
            - postgres
            - nginx

#    frontend:
#        build:
#            context: frontend
#            dockerfile: Dockerfile
#        stdin_open: true
#        volumes:
#            - './frontend:/app:cached'
#            - './frontend/node_modules:/app/node_modules:cached'
#        environment:
#            - NODE_ENV=development



volumes:
    db-data: